apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator-container
        image: 871154751090.dkr.ecr.eu-west-2.amazonaws.com/aggregator-service:latest
        ports:
        - containerPort: 8080