apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # or NodePort, ClusterIP based on requirements